### ISSUE TITLE
SAPStartSrv returns OCF_ERR_GENERIC (rc=1)

### ISSUE THREAD

**Issue by fmherschel** [SUSE/SAPStartSrv-resourceAgent#9]
When calling SAPStartSrv as probe (monitor interval 0) the RA returns 1 instead of 7.

**Comment by fmherschel** [comment]
This is triggered, because SAPStartSrv returns the result-rc of pgrep instead of translating into ocf returncodes.

**Comment by arbulu89** [comment]
Fixed in: https://github.com/SUSE/SAPStartSrv-resourceAgent/pull/10
